# DECINT runtime launcher — generated by DECINT EXE Maker. Do not edit by hand.
#
# This file is the real entry point of the built executable. It verifies the
# DECINT license for this product, shows the activation screen when there is
# none, then runs the wrapped application exactly as `python <entry>.py` would.
from __future__ import annotations

import json
import os
import runpy
import sys
import time

CONFIG = json.loads(r"""__DECINT_CONFIG_JSON__""")

LIC = CONFIG["licensing"]
PRODUCT_ID = CONFIG["product_id"]
PRODUCT_NAME = CONFIG["product_name"]

# Brand palette (matches the DECINT console).
PLATE, PANEL, INK, MUTED, VIOLET, GOOD, BAD = (
    "#10121C", "#171A28", "#E6E6F0", "#8A8FA8", "#8D5BF6", "#3DDC97", "#FF5C7A")


def _exe_dir() -> str:
    base = sys.executable if getattr(sys, "frozen", False) else __file__
    return os.path.dirname(os.path.abspath(base))


def _close_splash() -> None:
    # Only touch pyi_splash when the bootloader actually opened a splash screen:
    # importing the stub without one logs a warning traceback to the console.
    if "_PYI_SPLASH_IPC" not in os.environ and "pyi_splash" not in sys.modules:
        return
    try:
        import pyi_splash
        if pyi_splash.is_alive():
            pyi_splash.close()
    except Exception:
        pass


def _run_app() -> None:
    _close_splash()
    if CONFIG.get("chdir_to_bundle") and getattr(sys, "frozen", False):
        os.chdir(getattr(sys, "_MEIPASS", _exe_dir()))
    entry = CONFIG["entry_module"]
    if CONFIG.get("entry_callable"):
        import importlib
        mod = importlib.import_module(entry)
        rc = getattr(mod, CONFIG["entry_callable"])()
        sys.exit(rc if isinstance(rc, int) else 0)
    runpy.run_module(entry, run_name="__main__", alter_sys=True)


def _export(payload: dict | None, trial_days_left: int | None = None) -> None:
    """Expose license facts to the wrapped app through the environment."""
    if payload:
        os.environ["DECINT_LICENSE_ID"] = str(payload.get("lid", ""))
        os.environ["DECINT_LICENSE_CUSTOMER"] = str(payload.get("cust", ""))
        os.environ["DECINT_LICENSE_EXPIRES"] = str(int(payload["exp"]))
        os.environ["DECINT_LICENSE_FEATURES"] = ",".join(payload.get("feat") or [])
        os.environ["DECINT_LICENSE_MODE"] = "licensed"
    else:
        os.environ["DECINT_LICENSE_MODE"] = "trial"
        os.environ["DECINT_TRIAL_DAYS_LEFT"] = str(trial_days_left or 0)


# ────────────────────────── activation: console ──────────────────────────

def _activate_console(message: str, machine: str) -> str | None:
    print(f"\n  {PRODUCT_NAME} — licensed by DECINT")
    print("  " + "─" * 60)
    if message:
        print(f"  {message}")
    print(f"  Machine ID : {machine}")
    if LIC.get("vendor_contact"):
        print(f"  Get a key  : {LIC['vendor_contact']}")
    print("  Paste your license key (or press Enter to quit):")
    try:
        key = input("  > ").strip()
    except (EOFError, KeyboardInterrupt):
        return None
    return key or None


# ──────────────────────────── activation: Tk ────────────────────────────

def _activate_tk(message: str, machine: str, verifier) -> str | None:
    import tkinter as tk
    from tkinter import font as tkfont

    result: dict = {"key": None}
    root = tk.Tk()
    root.title(f"{PRODUCT_NAME} — Activation")
    root.configure(bg=PLATE)
    root.resizable(False, False)
    try:
        root.iconbitmap(default=os.path.join(getattr(sys, "_MEIPASS", _exe_dir()),
                                             "decint_rt", "decint.ico"))
    except Exception:
        pass

    mono = tkfont.Font(family="Consolas" if sys.platform == "win32" else "DejaVu Sans Mono", size=10)
    ui = tkfont.Font(family="Segoe UI" if sys.platform == "win32" else "DejaVu Sans", size=10)
    big = tkfont.Font(family=ui.cget("family"), size=15, weight="bold")

    pad = {"padx": 24}
    wrap = tk.Frame(root, bg=PLATE)
    wrap.pack(fill="both", expand=True, padx=8, pady=8)

    head = tk.Frame(wrap, bg=PLATE)
    head.pack(fill="x", pady=(14, 4), **pad)
    tk.Label(head, text="▲", fg=VIOLET, bg=PLATE, font=big).pack(side="left", padx=(0, 10))
    tk.Label(head, text=PRODUCT_NAME, fg=INK, bg=PLATE, font=big).pack(side="left")
    tk.Label(head, text="licensed by DECINT", fg=MUTED, bg=PLATE, font=ui).pack(side="right")

    status_var = tk.StringVar(value=message)
    status = tk.Label(wrap, textvariable=status_var, fg=BAD if message else MUTED, bg=PLATE,
                      font=ui, wraplength=520, justify="left", anchor="w")
    status.pack(fill="x", pady=(6, 10), **pad)

    mid_row = tk.Frame(wrap, bg=PANEL)
    mid_row.pack(fill="x", **pad)
    tk.Label(mid_row, text="Machine ID", fg=MUTED, bg=PANEL, font=ui).pack(side="left", padx=12, pady=10)
    mid_entry = tk.Entry(mid_row, font=mono, fg=INK, bg=PANEL, relief="flat",
                         insertbackground=INK, readonlybackground=PANEL, width=22, justify="center")
    mid_entry.insert(0, machine)
    mid_entry.configure(state="readonly")
    mid_entry.pack(side="left", pady=10)

    def copy_mid():
        root.clipboard_clear()
        root.clipboard_append(machine)
        status_var.set("Machine ID copied. Send it to your vendor to receive a bound key.")
        status.configure(fg=GOOD)

    tk.Button(mid_row, text="Copy", command=copy_mid, fg=INK, bg="#22263A", activebackground=VIOLET,
              activeforeground=INK, relief="flat", font=ui, padx=12).pack(side="right", padx=12)

    tk.Label(wrap, text="License key", fg=MUTED, bg=PLATE, font=ui, anchor="w").pack(fill="x", pady=(14, 4), **pad)
    box = tk.Text(wrap, height=6, width=68, font=mono, fg=INK, bg=PANEL, relief="flat",
                  insertbackground=INK, wrap="char", padx=10, pady=8,
                  highlightthickness=1, highlightbackground="#2A2E44", highlightcolor=VIOLET)
    box.pack(**pad)
    box.focus_set()

    def paste():
        try:
            box.delete("1.0", "end")
            box.insert("1.0", root.clipboard_get())
        except tk.TclError:
            pass

    def submit(_evt=None):
        key = box.get("1.0", "end").strip()
        if not key:
            status_var.set("Paste the license key you received from your vendor.")
            status.configure(fg=BAD)
            return
        ok, msg = verifier(key)
        if ok:
            result["key"] = key
            root.destroy()
        else:
            status_var.set(msg)
            status.configure(fg=BAD)
        return "break"   # keep Ctrl+Enter from inserting a newline into the key box

    def quit_():
        root.destroy()

    btns = tk.Frame(wrap, bg=PLATE)
    btns.pack(fill="x", pady=(14, 18), **pad)
    tk.Button(btns, text="Activate", command=submit, fg=INK, bg=VIOLET, activebackground="#A47CFF",
              activeforeground=INK, relief="flat", font=ui, padx=18, pady=6).pack(side="right")
    tk.Button(btns, text="Paste", command=paste, fg=INK, bg="#22263A", activebackground="#2E3350",
              activeforeground=INK, relief="flat", font=ui, padx=14, pady=6).pack(side="right", padx=8)
    tk.Button(btns, text="Quit", command=quit_, fg=MUTED, bg=PLATE, activebackground=PLATE,
              activeforeground=INK, relief="flat", font=ui, padx=10, pady=6).pack(side="left")
    if LIC.get("vendor_contact"):
        tk.Label(btns, text=f"Get a key: {LIC['vendor_contact']}", fg=MUTED, bg=PLATE,
                 font=ui).pack(side="left", padx=(16, 0))

    root.bind("<Control-Return>", submit)
    root.protocol("WM_DELETE_WINDOW", quit_)
    root.eval("tk::PlaceWindow . center")
    root.mainloop()
    return result["key"]


def _notice(title: str, text: str) -> None:
    """Non-fatal message (expiry warning, trial countdown)."""
    if LIC.get("ui") == "tk":
        try:
            import tkinter as tk
            from tkinter import messagebox
            r = tk.Tk()
            r.withdraw()
            messagebox.showwarning(title, text, parent=r)
            r.destroy()
            return
        except Exception:
            pass
    print(f"\n  [{title}] {text}\n")


# ─────────────────────────────── main ───────────────────────────────

def main() -> None:
    if not LIC.get("enabled"):
        return _run_app()

    from decint_rt import licensing

    n, e = int(LIC["public_n"]), int(LIC["public_e"])
    machine = licensing.machine_id() if LIC.get("bind_machine") else None
    mid_display = licensing.machine_id()

    def check(text):
        return licensing.verify_license(text, n, e, product_id=PRODUCT_ID, machine=machine)

    def verifier(text):
        try:
            check(text)
            return True, "ok"
        except licensing.LicenseError as ex:
            return False, str(ex)

    try:
        licensing.check_clock(PRODUCT_ID)
    except licensing.LicenseError as ex:
        _notice(PRODUCT_NAME, str(ex))
        sys.exit(3)

    message = ""
    attempt_failed = False
    while True:
        payload = None
        if not attempt_failed:
            text = licensing.find_license(PRODUCT_ID, _exe_dir())
            if text:
                try:
                    payload = check(text)
                except licensing.LicenseError as ex:
                    message = str(ex)
            else:
                trial_days = int(LIC.get("trial_days") or 0)
                active, left = licensing.trial_state(PRODUCT_ID, trial_days)
                if active:
                    _export(None, left)
                    if left <= licensing.EXPIRY_WARNING_DAYS:
                        _notice(PRODUCT_NAME, f"Trial: {left} day(s) left. Enter a license key to keep using it.")
                    return _run_app()
                message = ("Trial period is over. Enter a license key to continue." if trial_days else
                           "This copy is not activated. Enter your license key to continue.")
            if payload:
                _export(payload)
                left = licensing.days_left(payload)
                if left <= licensing.EXPIRY_WARNING_DAYS:
                    _notice(PRODUCT_NAME, f"Your license expires in {left} day(s) "
                                          f"({licensing.fmt_date(payload['exp'])}). "
                                          f"Contact {LIC.get('vendor_contact') or 'your vendor'} to renew.")
                return _run_app()

        attempt_failed = False
        _close_splash()
        if LIC.get("ui") == "tk":
            key = _activate_tk(message, mid_display, verifier)
        else:
            key = _activate_console(message, mid_display)
        if not key:
            sys.exit(3)
        ok, msg = verifier(key)
        if ok:
            licensing.save_license(PRODUCT_ID, key)
            os.environ.pop("DECINT_LICENSE", None)
            message = ""
        else:
            message = msg
            attempt_failed = True
            time.sleep(0.2)


if __name__ == "__main__":
    if sys.platform == "win32":
        import multiprocessing
        multiprocessing.freeze_support()   # harmless in the parent; required for spawned children
    main()
