// Small inline icon set (Phosphor-style paths), sized via `size` prop.
import * as React from "react";

type P = { size?: number; className?: string; style?: React.CSSProperties };
const box = (size = 16) => ({ width: size, height: size, viewBox: "0 0 256 256" });

/**
 * The DECINT mark — two curves sweeping up to a centre peak, straight flanks,
 * point at the bottom.
 *
 * It is EMPTY on purpose. Nothing goes inside the shield: no letter, no
 * keyhole, no crosshair. The silhouette plus the negative space is the whole
 * mark, which is what lets it survive down to 16px and read the same on the
 * plate, in the nav and in the footer.
 *
 * Geometry is generated by scripts/make_favicon.py (`shield_svg_hollow`) so the
 * component and the favicon set are literally the same shape. If you change the
 * stroke weight, change it there and regenerate both — do not hand-edit this
 * path, or the icon and the wordmark will quietly stop matching.
 */
export function Shield({ size = 16, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M128,10Q173.1,10 222,52.5L222,132.7Q222,213 128,246Q34,213 34,132.7L34,52.5Q82.9,10 128,10ZM128,31Q163,31 201,65.9L201,131.9Q201,197.8 128,225Q55,197.8 55,131.9L55,65.9Q93,31 128,31Z"
      />
    </svg>
  );
}

export function Search({ size = 16, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z" />
    </svg>
  );
}

export function CaretDown({ size = 12, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M213.66,101.66l-80,80a8,8,0,0,1-11.32,0l-80-80A8,8,0,0,1,53.66,90.34L128,164.69l74.34-74.35a8,8,0,0,1,11.32,11.32Z" />
    </svg>
  );
}

export function Check({ size = 14, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M173.66,98.34a8,8,0,0,1,0,11.32l-56,56a8,8,0,0,1-11.32,0l-24-24a8,8,0,0,1,11.32-11.32L112,148.69l50.34-50.35A8,8,0,0,1,173.66,98.34Z" />
    </svg>
  );
}

export function Copy({ size = 14, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M216,32H88a8,8,0,0,0-8,8V80H40a8,8,0,0,0-8,8V216a8,8,0,0,0,8,8H168a8,8,0,0,0,8-8V176h40a8,8,0,0,0,8-8V40A8,8,0,0,0,216,32ZM160,208H48V96H160Zm48-48H176V88a8,8,0,0,0-8-8H96V48H208Z" />
    </svg>
  );
}

export function ArrowRight({ size = 14, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M221.66,133.66l-72,72a8,8,0,0,1-11.32-11.32L196.69,136H40a8,8,0,0,1,0-16H196.69L138.34,61.66a8,8,0,0,1,11.32-11.32l72,72A8,8,0,0,1,221.66,133.66Z" />
    </svg>
  );
}

/* ── Tool glyphs (/tools showcase) ────────────────────────────────────────
   Stroke-based rather than filled like the set above, because at 22–28px a
   filled glyph next to the hollow shield reads as a second, heavier brand
   mark. `vectorEffect` is deliberately not set: these never scale below 18px.
   All inherit `currentColor`, so the violet comes from the parent. */

const stroke = {
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 16,
  strokeLinecap: "round" as const,
  strokeLinejoin: "round" as const,
};

/** Leak search — a stack of records. */
export function Database({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <ellipse cx="128" cy="60" rx="84" ry="32" {...stroke} />
      <path d="M44,60 V196 a84,32 0 0 0 168,0 V60" {...stroke} />
      <path d="M44,128 a84,32 0 0 0 168,0" {...stroke} />
    </svg>
  );
}

/** Dark-web search — the layers of an onion circuit, seen end-on. */
export function Onion({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <circle cx="128" cy="128" r="96" {...stroke} />
      <circle cx="128" cy="128" r="58" {...stroke} />
      <circle cx="128" cy="128" r="18" fill="currentColor" stroke="none" />
    </svg>
  );
}

/** Password checker — a key. */
export function Key({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <circle cx="84" cy="128" r="44" {...stroke} />
      <path d="M128,128 H220 M184,128 V164 M214,128 V156" {...stroke} />
    </svg>
  );
}

/** IP lookup — a globe: the address placed on the map. */
export function Globe({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <circle cx="128" cy="128" r="96" {...stroke} />
      <ellipse cx="128" cy="128" rx="40" ry="96" {...stroke} />
      <path d="M32,128 H224" {...stroke} />
    </svg>
  );
}

/** Phone lookup — a handset with the keypad's centre row. */
export function Phone({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <rect x="68" y="28" width="120" height="200" rx="20" {...stroke} />
      <path d="M112,196 H144" {...stroke} />
      <circle cx="100" cy="112" r="9" fill="currentColor" stroke="none" />
      <circle cx="128" cy="112" r="9" fill="currentColor" stroke="none" />
      <circle cx="156" cy="112" r="9" fill="currentColor" stroke="none" />
    </svg>
  );
}

/** Spider / correlation — a central node with three links fanning out to
 *  satellite nodes. The pivot graph, in one glyph. */
export function Spider({ size = 24, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <path d="M128,128 L56,64 M128,128 L212,96 M128,128 L104,210" {...stroke} />
      <circle cx="128" cy="128" r="24" {...stroke} />
      <circle cx="52" cy="60" r="16" {...stroke} />
      <circle cx="216" cy="92" r="16" {...stroke} />
      <circle cx="100" cy="214" r="16" {...stroke} />
    </svg>
  );
}

/* ── Payment marks (pricing / checkout) ───────────────────────────────────
   Generic glyphs on purpose. Card-network and processor logos are trademarks
   with their own usage rules and exact geometry; an approximation of one is
   worse than not drawing it. The brand names are set in text beside these,
   which is nominative use and needs no artwork. */

/** Card rail. */
export function CreditCard({ size = 20, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <rect x="24" y="56" width="208" height="144" rx="20" {...stroke} />
      <path d="M24,108 H232" {...stroke} />
      <path d="M60,160 H100" {...stroke} />
    </svg>
  );
}

/** Crypto rail. */
export function Coin({ size = 20, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <circle cx="128" cy="128" r="94" {...stroke} />
      <path d="M104,72 V184 M136,72 V184" {...stroke} />
      <path d="M92,100 H146 a24,24 0 0 1 0,48 H92 h58 a24,24 0 0 1 0,48 H92" {...stroke} />
    </svg>
  );
}

/** Shown beside "card details never reach this server". */
export function Lock({ size = 16, className, style }: P) {
  return (
    <svg {...box(size)} className={className} style={style} aria-hidden>
      <rect x="44" y="108" width="168" height="112" rx="18" {...stroke} />
      <path d="M92,108 V76 a36,36 0 0 1 72,0 v32" {...stroke} />
    </svg>
  );
}

/** Profile — a head-and-shoulders bust in a circle. */
export function UserCircle({ size = 16, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24ZM74.08,197.5a72,72,0,0,1,107.84,0,87.83,87.83,0,0,1-107.84,0ZM96,120a32,32,0,1,1,32,32A32,32,0,0,1,96,120Zm97.76,66.41a88.07,88.07,0,0,0-43.18-35.54,48,48,0,1,0-45.16,0,88.07,88.07,0,0,0-43.18,35.54,88,88,0,1,1,131.52,0Z" />
    </svg>
  );
}

/** Support — a life ring, for the ticket system. */
export function LifeBuoy({ size = 16, className, style }: P) {
  return (
    <svg {...box(size)} fill="currentColor" className={className} style={style} aria-hidden>
      <path d="M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm67.72,45.17-26,26a48.29,48.29,0,0,0-13.9-13.9l26-26A89,89,0,0,1,195.72,69.17ZM160,128a32,32,0,1,1-32-32A32,32,0,0,1,160,128ZM88.28,42.19l26,26a48.29,48.29,0,0,0-13.9,13.9l-26-26A89.59,89.59,0,0,1,88.28,42.19ZM60.28,186.83l26-26a48.29,48.29,0,0,0,13.9,13.9l-26,26A89,89,0,0,1,60.28,186.83Zm107.44,13.9-26-26a48.29,48.29,0,0,0,13.9-13.9l26,26A89.59,89.59,0,0,1,167.72,200.73Z" />
    </svg>
  );
}
